FROM registry.ci.openshift.org/origin/4.10:machine-config-operator as mcd
FROM registry.ci.openshift.org/origin/4.10:artifacts as artifacts

FROM quay.io/coreos-assembler/coreos-assembler:latest

COPY --from=mcd /usr/bin/machine-config-daemon /resources/overrides/rootfs/usr/libexec/machine-config-daemon
COPY --from=artifacts /srv/repo/*.rpm /resources/srv/okd-repo/
