on:
  push: {}

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  prepare:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: "projects/649394681476/locations/global/workloadIdentityPools/github/providers/oidc"
          service_account: okd-machine-os@gentoli.iam.gserviceaccount.com
      - shell: bash
        run: |
          docker buildx build -f Dockerfile.cosa \
            --tag us.gcr.io/gen-pub/okd-coreos-assembler:latest \
            --push

  build:
    needs:
      - prepare
    runs-on:
      - self-hosted
    container:
      image: us.gcr.io/gen-pub/okd-coreos-assembler:latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: /src
      - shell: bash
        run: |
          set -exuo pipefail
          export COSA_SKIP_OVERLAY=1
          
          cosa init /src --force
          
          # Create repo for OKD RPMs
          pushd /srv/okd-repo
            createrepo_c .
          popd
          
          # build ostree commit
          cosa fetch
          cosa build ostree
          
          # Create repo for OS Extensions
          mkdir -p /overlay/extensions
          pushd /overlay/extensions
            createrepo_c .
          popd
          
          echo "Building container"
          cosa upload-oscontainer --name "quay.io/vrutkovs/okd-os" --add-directory /overlay
        
