on:
  push: {}

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on:
      - self-hosted
    container:
      image: us.gcr.io/gen-pub/okd-coreos-assembler:latest
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          mkdir -p ./overlay.d/99okd/usr/libexec
          cp /usr/bin/machine-config-daemon ./overlay.d/99okd/usr/libexec/machine-config-daemon
          
          mkdir -p ./repo
          cp -r /files/okd-repo ./repo

      - shell: bash
        working-directory: /srv
        run: |
          set -exuo pipefail
          export COSA_SKIP_OVERLAY=1
          
          cosa init $GITHUB_WORKSPACE --force

          # Create repo for OKD RPMs
          pushd /srv/okd-repo
            createrepo_c .
          popd
          
          # build ostree commit
          cosa fetch
          cosa build ostree
          
          # Create repo for OS Extensions
          mkdir -p /overlay/extensions
          pushd /overlay/extensions
            createrepo_c .
          popd
          
          echo "Building container"
          cosa upload-oscontainer --name "quay.io/vrutkovs/okd-os" --add-directory /overlay
        
