name: Build Machine Image

on:
  push: {}

# permissions:
#   contents: 'read'
#   id-token: 'write'

jobs:
  build:
    runs-on:
      - self-hosted
    container:
      image: default-route-openshift-image-registry.apps.ocp.nsyd.tech/github-runners/okd-coreos-assembler:latest
      # privileged for kvm, expose runner's docker creds to podman, use _work for fsetxattr(security.selinux
      options: >-
        --privileged
        -v /runner/.docker/config.json:/github/home/.docker/config.json
        -v /runner/_work:/srv
    outputs:
      imageAndTag: ${{ steps.id.outputs.imageAndTag }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      # - id: 'auth'
      #   uses: 'google-github-actions/auth@v0'
      #   with:
      #     workload_identity_provider: "projects/649394681476/locations/global/workloadIdentityPools/github/providers/oidc"
      #     service_account: okd-machine-os@gentoli.iam.gserviceaccount.com

      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v0'

      # - name: Login OKD
      #   run: |
      #     cat /var/run/secrets/kubernetes.io/serviceaccount/token  | docker login -u some --password-stdin default-route-openshift-image-registry.apps.ocp.nsyd.tech

      #     # create link for cosa sudo
      #     cp -r ~/.config /root
      #     ln -s "$(which docker-credential-gcloud)" /usr/local/bin/

      - shell: bash
        run: |
          rsync -rv /resources/src/* .

      - shell: bash
        working-directory: /srv
        run: |
          set -exuo pipefail
          export COSA_SKIP_OVERLAY=1

          rsync -rv /resources/srv/* .

          cosa init $GITHUB_WORKSPACE --force --transient

          # Create repo for OKD RPMs
          pushd /srv/okd-repo
            createrepo_c .
          popd
          
          # build ostree commit
          cosa fetch
          cosa build ostree
          
          # Create repo for OS Extensions
          sudo mkdir -p /overlay/extensions
          pushd /overlay/extensions
            sudo createrepo_c .
          popd

      - name: Building container
        shell: bash
        working-directory: /srv
        run: |
          cosa upload-oscontainer --name "default-route-openshift-image-registry.apps.ocp.nsyd.tech/github-runners/okd-os" --add-directory /overlay

      - name: Output Build ID
        id: id
        working-directory: /srv
        run: |
          # https://github.com/coreos/coreos-assembler/blob/e02480568ba41280fc1d104dbb2c3143fda1f8da/src/cmd-upload-oscontainer#L38
          ID=$(cat builds/builds.json | jq -r '.builds[0].id')
          IMAGE_AND_TAG="default-route-openshift-image-registry.apps.ocp.nsyd.tech/github-runners/okd-os:$ID"
          echo $IMAGE_AND_TAG
          echo "::set-output name=imageAndTag::$IMAGE_AND_TAG"

      - name: Wait on Fail
        if: ${{ failure() }}
        shell: bash
        run: sleep infinity

  bundle:
    runs-on:
      - self-hosted
    needs: [build]
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: "projects/649394681476/locations/global/workloadIdentityPools/github/providers/oidc"
          service_account: okd-machine-os@gentoli.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Login OKD
        run: |
          cat /var/run/secrets/kubernetes.io/serviceaccount/token  | docker login -u some --password-stdin default-route-openshift-image-registry.apps.ocp.nsyd.tech

      - name: Set up Docker Context for Buildx
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            default-route-openshift-image-registry.apps.ocp.nsyd.tech/github-runners/okd-machine-os
            us.gcr.io/gen-pub/okd-machine-os
          tags: |
            type=sha,enable=true,priority=100,format=short

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.template
          push: true
          build-args: INITIAL_IMAGE=${{ needs.build.outputs.imageAndTag }}
          tags: ${{ steps.meta.outputs.tags }}
