on:
  push: {}

permissions:
  contents: 'read'
  id-token: 'write'

jobs:
  build:
    runs-on:
      - self-hosted
    container:
      image: us.gcr.io/gen-pub/okd-coreos-assembler:latest
      options: >-
        --privileged
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - shell: bash
        run: |
          rsync -rv /resources/src/* .

      - shell: bash
        working-directory: /srv
        run: |
          set -exuo pipefail
          export COSA_SKIP_OVERLAY=1

          rsync -rv /resources/srv/* .

          cosa init $GITHUB_WORKSPACE --force

          # Create repo for OKD RPMs
          pushd /srv/okd-repo
            createrepo_c .
          popd
          
          # build ostree commit
          cosa fetch
          cosa build ostree
          
          # Create repo for OS Extensions
          sudo mkdir -p /overlay/extensions
          pushd /overlay/extensions
            sudo createrepo_c .
          popd

      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: "projects/649394681476/locations/global/workloadIdentityPools/github/providers/oidc"
          service_account: okd-machine-os@gentoli.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Login GCR
        run: |
          gcloud auth configure-docker

      - name: Building container
        shell: bash
        working-directory: /srv
        run: |
          cosa upload-oscontainer --name "us.gcr.io/gen-pub/okd-os" --add-directory /overlay
        
