on:
  schedule:
    - cron: '1 6 * * SUN'
  workflow_dispatch: { }
  # tmp
  push: { }

jobs:
  prepare:
    runs-on:
      - self-hosted
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: "projects/649394681476/locations/global/workloadIdentityPools/github/providers/oidc"
          service_account: okd-machine-os@gentoli.iam.gserviceaccount.com

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Login GCR
        run: |
          gcloud auth configure-docker

      - name: Set up Docker Context for Buildx
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.cosa
          push: true
          tags: us.gcr.io/gen-pub/okd-coreos-assembler:latest
